# sudo is required when docker is used
sudo: required 
services:
  - docker
    
before_install:
  - docker build -t vcml10/docker-react -f Dockerfile.dev .

script:
  - docker run vcml10/docker-react npm run test -- --coverage
